export interface Deal {
  id: string;
  businessName: string;
  businessLogo: string;
  agreedRate: number;
  status: "Pending" | "In Progress" | "Completed" | "Cancelled";
  platform: string;
  contentType: string;
  contractTerms: string;
  date: string;
  createdAt: string;
  updatedAt: string;
}

// The mockDeals array
export const mockDeals: Deal[] = [
  {
    id: "1",
    businessName: "TechGiant",
    businessLogo: "/placeholder.svg?height=50&width=50",
    agreedRate: 1500,
    status: "In Progress",
    platform: "Instagram",
    contentType: "Post",
    contractTerms: "Instagram post about the latest smartphone",
    date: "2023-09-15",
    createdAt: "2023-09-01",
    updatedAt: "2023-09-10",
  },
  {
    id: "2",
    businessName: "FashionBrand",
    businessLogo: "/placeholder.svg?height=50&width=50",
    agreedRate: 800,
    status: "Pending",
    platform: "Youtube",
    contentType: "Video",
    contractTerms: "YouTube video showcasing summer collection",
    date: "2023-09-20",
    createdAt: "2023-09-05",
    updatedAt: "2023-09-15",
  },
  {
    id: "3",
    businessName: "FoodChain",
    businessLogo: "/placeholder.svg?height=50&width=50",
    agreedRate: 2000,
    status: "Completed",
    platform: "Instagram",
    contentType: "Story",
    contractTerms: "Instagram story about new menu items",
    date: "2023-09-10",
    createdAt: "2023-09-01",
    updatedAt: "2023-09-12",
  },
  {
    id: "4",
    businessName: "TravelCo",
    businessLogo: "/placeholder.svg?height=50&width=50",
    agreedRate: 1200,
    status: "Pending",
    platform: "Instagram",
    contentType: "Post",
    contractTerms: "Instagram post about travel destinations",
    date: "2023-09-25",
    createdAt: "2023-09-08",
    updatedAt: "2023-09-18",
  },
  {
    id: "5",
    businessName: "FitnessBrand",
    businessLogo: "/placeholder.svg?height=50&width=50",
    agreedRate: 1000,
    status: "Completed",
    platform: "Instagram",
    contentType: "Post",
    contractTerms: "Instagram post promoting fitness products",
    date: "2023-09-05",
    createdAt: "2023-09-01",
    updatedAt: "2023-09-07",
  },
  {
    id: "6",
    businessName: "TechGiant",
    businessLogo: "/placeholder.svg?height=50&width=50",
    agreedRate: 1500,
    status: "In Progress",
    platform: "Instagram",
    contentType: "Post",
    contractTerms: "Instagram post about the latest smartphone",
    date: "2023-09-15",
    createdAt: "2023-09-01",
    updatedAt: "2023-09-10",
  },
  {
    id: "7",
    businessName: "FashionBrand",
    businessLogo: "/placeholder.svg?height=50&width=50",
    agreedRate: 800,
    status: "Pending",
    platform: "YouTube",
    contentType: "Video",
    contractTerms: "YouTube video showcasing summer collection",
    date: "2023-09-20",
    createdAt: "2023-09-05",
    updatedAt: "2023-09-15",
  },
  {
    id: "8",
    businessName: "FoodChain",
    businessLogo: "/placeholder.svg?height=50&width=50",
    agreedRate: 2000,
    status: "Completed",
    platform: "Instagram",
    contentType: "Story",
    contractTerms: "Instagram story about new menu items",
    date: "2023-09-10",
    createdAt: "2023-09-01",
    updatedAt: "2023-09-12",
  },
  {
    id: "9",
    businessName: "TravelCo",
    businessLogo: "/placeholder.svg?height=50&width=50",
    agreedRate: 1200,
    status: "Pending",
    platform: "Instagram",
    contentType: "Post",
    contractTerms: "Instagram post about travel destinations",
    date: "2023-09-25",
    createdAt: "2023-09-08",
    updatedAt: "2023-09-18",
  },
  {
    id: "10",
    businessName: "FitnessBrand",
    businessLogo: "/placeholder.svg?height=50&width=50",
    agreedRate: 1000,
    status: "Completed",
    platform: "Instagram",
    contentType: "Post",
    contractTerms: "Instagram post promoting fitness products",
    date: "2023-09-05",
    createdAt: "2023-09-01",
    updatedAt: "2023-09-07",
  },
];
