export const mockOpportunities = [
  {
    _id: "1",
    title: "Fitness Influencer Needed for Protein Shake Campaign",
    description:
      "We're looking for fitness enthusiasts to promote our new line of protein shakes. Create engaging content showcasing how our product fits into your workout routine.",
    category: "Fitness",
    budget: 1000,
    platform: ["Instagram", "TikTok"],
    contentType: ["Post", "Story", "Reels"],
    followerCountRequirement: 10000,
    dealType: "collaboration",
    business: {
      _id: "b1",
      name: "FitFuel Nutrition",
      logo: "https://www.shutterstock.com/image-vector/circle-line-simple-design-logo-600nw-2174926871.jpg",
    },
    deadline: "2024-05-01",
    location: "Any",
    createdAt: "2024-03-15",
  },
  {
    _id: "2",
    title: "Tech Reviewer Wanted for Latest Smartphone",
    description:
      "We're seeking tech-savvy influencers to review our cutting-edge smartphone. Provide an in-depth analysis of its features and performance in a video format.",
    category: "Tech",
    budget: 1500,
    platform: ["YouTube"],
    contentType: ["Video Collaboration"],
    followerCountRequirement: 50000,
    dealType: "job",
    business: {
      _id: "b2",
      name: "TechNova",
      logo: "https://st3.depositphotos.com/43745012/44906/i/450/depositphotos_449066958-stock-photo-financial-accounting-logo-financial-logo.jpg",
    },
    deadline: "2024-04-15",
    location: "Any",
    createdAt: "2024-03-10",
  },
  {
    _id: "3",
    title: "Travel Vlogger for Luxury Resort Promotion",
    description:
      "We're looking for travel enthusiasts to showcase our luxury resort. Create a series of vlogs highlighting the amenities, local attractions, and overall experience.",
    category: "Travel",
    budget: 3000,
    platform: ["YouTube", "Instagram"],
    contentType: ["Video Collaboration", "Post", "Story"],
    followerCountRequirement: 100000,
    dealType: "collaboration",
    business: {
      _id: "b3",
      name: "Paradise Escapes",
      logo: "https://cdn.pixabay.com/photo/2015/05/22/19/01/business-779542_1280.jpg",
    },
    deadline: "2024-06-30",
    location: "Bali, Indonesia",
    createdAt: "2024-03-20",
  },
  {
    _id: "4",
    title: "Fashion Blogger Needed for Clothing Line Promotion",
    description:
      "We're seeking fashion influencers to promote our latest collection. Create stylish lookbooks and share outfit ideas featuring our clothing items.",
    category: "Fashion",
    budget: 1200,
    platform: ["Instagram", "TikTok"],
    contentType: ["Post", "Story"],
    followerCountRequirement: 20000,
    dealType: "collaboration",
    business: {
      _id: "b4",
      name: "ChicStyle Boutique",
      logo: "https://www.shutterstock.com/image-vector/clothing-logo-design-vector-illustration-600w-1576662597.jpg",
    },
    deadline: "2024-05-15",
    location: "Any",
    createdAt: "2024-03-25",
  },
  {
    _id: "5",
    title: "Food Influencer Wanted for Restaurant Promotion",
    description:
      "We're looking for foodies to review our restaurant and menu items. Capture mouth-watering photos and videos to entice your audience to dine with us.",
    category: "Food",
    budget: 800,
    platform: ["Instagram"],
    contentType: ["Post", "Story"],
    followerCountRequirement: 15000,
    dealType: "collaboration",
    business: {
      _id: "b5",
      name: "TasteBuds Eatery",
      logo: "https://www.shutterstock.com/image-vector/food-logo-design-vector-illustration-600w-1576662596.jpg",
    },
    deadline: "2024-09-30",
    location: "New York City, USA",
    createdAt: "2024-09-05",
  },
  {
    _id: "6",
    title: "Beauty Influencer Needed for Makeup Brand Promotion",
    description:
      "We're seeking beauty gurus to showcase our latest makeup products. Create stunning makeup looks using our items and share your honest reviews with your followers.",
    category: "Beauty",
    budget: 1000,
    platform: ["YouTube", "Instagram"],
    contentType: ["Video Collaboration", "Post", "Story"],
    followerCountRequirement: 30000,
    dealType: "collaboration",
    business: {
      _id: "b6",
      name: "GlamGlow Cosmetics",
      logo: "https://www.shutterstock.com/image-vector/cosmetic-logo-design-vector-illustration-600w-1576662595.jpg",
    },
    deadline: "2024-05-10",
    location: "Any",
    createdAt: "2024-03-01",
  },
  {
    _id: "7",
    title: "Gaming Streamer Wanted for New Video Game Launch",
    description:
      "We're looking for gamers to play and review our upcoming video game. Stream your gameplay live on Twitch and engage with your audience to build hype.",
    category: "Gaming",
    budget: 2000,
    platform: ["Twitch"],
    contentType: ["Live Stream"],
    followerCountRequirement: 25000,
    dealType: "job",
    business: {
      _id: "b7",
      name: "PixelPlay Games",
      logo: "https://www.shutterstock.com/image-vector/game-logo-design-vector-illustration-600w-1576662594.jpg",
    },
    deadline: "2024-04-30",
    location: "Any",
    createdAt: "2024-03-05",
  },
  {
    _id: "8",
    title: "Pet Influencer Needed for Pet Product Promotion",
    description:
      "We're seeking pet lovers to showcase our new line of pet accessories. Create adorable content featuring your furry friends using our products.",
    category: "Pets",
    budget: 500,
    platform: ["Instagram"],
    contentType: ["Post", "Story"],
    followerCountRequirement: 10000,
    dealType: "collaboration",
    business: {
      _id: "b8",
      name: "Paws & Play",
      logo: "https://www.shutterstock.com/image-vector/pet-logo-design-vector-illustration-600w-1576662593.jpg",
    },
    deadline: "2024-06-15",
    location: "Any",
    createdAt: "2024-03-12",
  },
  {
    _id: "9",
    title: "Interior Design Blogger Wanted for Home Decor Brand",
    description:
      "We're looking for interior design enthusiasts to showcase our home decor products. Create aesthetically pleasing content featuring our items in various settings.",
    category: "Home Decor",
    budget: 800,
    platform: ["Instagram"],
    contentType: ["Post", "Story"],
    followerCountRequirement: 15000,
    dealType: "collaboration",
    business: {
      _id: "b9",
      name: "UrbanNest Decor",
      logo: "https://www.shutterstock.com/image-vector/home-logo-design-vector-illustration-600w-1576662592.jpg",
    },
    deadline: "2024-05-20",
    location: "Any",
    createdAt: "2024-03-08",
  },
  {
    _id: "10",
    title: "Music Influencer Needed for Album Release Promotion",
    description:
      "We're seeking music enthusiasts to promote our latest album release. Share your favorite tracks, behind-the-scenes footage, and engage with your audience.",
    category: "Music",
    budget: 1000,
    platform: ["Instagram", "TikTok"],
    contentType: ["Post", "Story"],
    followerCountRequirement: 20000,
    dealType: "collaboration",
    business: {
      _id: "b10",
      name: "SoundVibe Records",
      logo: "https://www.shutterstock.com/image-vector/music-logo-design-vector-illustration-600w-1576662591.jpg",
    },
    deadline: "2024-04-25",
    location: "Any",
    createdAt: "2024-03-18",
  },
  {
    _id: "11",
    title: "Health & Wellness Blogger Wanted for Supplement Brand",
    description:
      "We're looking for health and wellness enthusiasts to promote our line of supplements. Share your personal journey and the benefits of our products with your audience.",
    category: "Health & Wellness",
    budget: 1200,
    platform: ["YouTube", "Instagram"],
    contentType: ["Video Collaboration", "Post", "Story"],
    followerCountRequirement: 30000,
    dealType: "collaboration",
    business: {
      _id: "b11",
      name: "VitaLife Wellness",
      logo: "https://www.shutterstock.com/image-vector/health-logo-design-vector-illustration-600w-1576662590.jpg",
    },
    deadline: "2024-06-10",
    location: "Any",
    createdAt: "2024-03-22",
  },
  {
    _id: "12",
    title: "Art Influencer Needed for Art Supply Promotion",
    description:
      "We're seeking artists to showcase our high-quality art supplies. Create stunning artwork using our products and share your creative process with your followers.",
    category: "Art",
    budget: 800,
    platform: ["Instagram"],
    contentType: ["Post", "Story"],
    followerCountRequirement: 10000,
    dealType: "collaboration",
    business: {
      _id: "b12",
      name: "CreativeCanvas",
      logo: "https://www.shutterstock.com/image-vector/art-logo-design-vector-illustration-600w-1576662589.jpg",
    },
    deadline: "2024-05-05",
    location: "Any",
    createdAt: "2024-03-02",
  },
  {
    _id: "13",
    title: "Book Reviewer Wanted for New Book Launch",
    description:
      "We're looking for book lovers to review our latest novel. Share your thoughts, favorite quotes, and engage with your audience to generate interest in the book.",
    category: "Books",
    budget: 500,
    platform: ["YouTube", "Instagram"],
    contentType: ["Video Collaboration", "Post", "Story"],
    followerCountRequirement: 10000,
    dealType: "collaboration",
    business: {
      _id: "b13",
      name: "NovelReads Publishing",
      logo: "https://www.shutterstock.com/image-vector/book-logo-design-vector-illustration-600w-1576662588.jpg",
    },
    deadline: "2024-04-20",
    location: "Any",
    createdAt: "2024-03-28",
  },
  {
    _id: "14",
    title: "DIY Influencer Needed for Craft Supply Promotion",
    description:
      "We're seeking DIY enthusiasts to showcase our craft supplies. Create fun and engaging DIY projects using our products and share your tutorials with your followers.",
    category: "DIY & Crafts",
    budget: 600,
    platform: ["YouTube", "Instagram"],
    contentType: ["Video Collaboration", "Post", "Story"],
    followerCountRequirement: 15000,
    dealType: "collaboration",
    business: {
      _id: "b14",
      name: "CraftyCorner",
      logo: "https://www.shutterstock.com/image-vector/craft-logo-design-vector-illustration-600w-1576662587.jpg",
    },
    deadline: "2024-05-25",
    location: "Any",
    createdAt: "2024-03-17",
  },
  {
    _id: "15",
    title: "Parenting Blogger Wanted for Kids' Product Promotion",
    description:
      "We're looking for parenting influencers to promote our kids' products. Share your parenting tips, product reviews, and engage with your audience to build trust.",
    category: "Parenting",
    budget: 700,
    platform: ["Instagram"],
    contentType: ["Post", "Story"],
    followerCountRequirement: 20000,
    dealType: "collaboration",
    business: {
      _id: "b15",
      name: "TinyTots Co.",
      logo: "https://www.shutterstock.com/image-vector/kids-logo-design-vector-illustration-600w-1576662586.jpg",
    },
    deadline: "2024-06-05",
    location: "Any",
    createdAt: "2024-03-19",
  },
  {
    _id: "16",
    title: "Sports Blogger Needed for Fitness Apparel Brand",
    description:
      "We're seeking sports enthusiasts to promote our fitness apparel. Create workout videos, share fitness tips, and showcase our products in action.",
    category: "Sports",
    budget: 900,
    platform: ["YouTube", "Instagram"],
    contentType: ["Video Collaboration", "Post", "Story"],
    followerCountRequirement: 25000,
    dealType: "collaboration",
    business: {
      _id: "b16",
      name: "ActiveWear Co.",
      logo: "https://www.shutterstock.com/image-vector/sport-logo-design-vector-illustration-600w-1576662585.jpg",
    },
    deadline: "2024-05-30",
    location: "Any",
    createdAt: "2024-03-23",
  },
];
