export const notifications = [
  {
    id: 1,
    avatar: "/placeholder.svg?height=40&width=40",
    name: "Alice Johnson",
    action: "liked your post",
    time: "2 minutes ago",
    unread: true,
    icon: "ThumbsUp",
  },
  {
    id: 2,
    avatar: "/placeholder.svg?height=40&width=40",
    name: "Bob Smith",
    action: "commented on your photo",
    time: "1 hour ago",
    unread: true,
    icon: "MessageSquare",
  },
  {
    id: 3,
    avatar: "/placeholder.svg?height=40&width=40",
    name: "Charlie Brown",
    action: "mentioned you in a comment",
    time: "3 hours ago",
    unread: false,
    icon: "User",
  },
  {
    id: 4,
    avatar: "/placeholder.svg?height=40&width=40",
    name: "Diana Prince",
    action: "sent you a message",
    time: "Yesterday",
    unread: false,
    icon: "MessageSquare",
  },
  {
    id: 5,
    avatar: "/placeholder.svg?height=40&width=40",
    name: "Ethan Hunt",
    action: "started following you",
    time: "2 days ago",
    unread: false,
    icon: "User",
  },
  {
    id: 5,
    avatar: "/placeholder.svg?height=40&width=40",
    name: "Ethan Hunt",
    action: "started following you",
    time: "2 days ago",
    unread: false,
    icon: "User",
  },
];
