"use client ";
import type { Metadata } from "next";
import "../globals.css";
import SearchBar from "@/components/SearchBar";
import Sidebar from "@/components/Sidebar";
import { ReduxProvider } from "../providers/redux-providers";
import TopLoader from "@/components/TopLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body className="antialiased h-screen">
        <ReduxProvider>
          <TopLoader />
          <div className="flex h-full w-full">
            <Sidebar />
            <div className="flex-1 flex flex-col bg-gray-950">
              <SearchBar />
              <div className="flex-1 overflow-y-hidden">{children}</div>
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
