import type { Metadata } from "next";
import "../globals.css";
import { ReduxProvider } from "../providers/redux-providers";
import MainLayout from "./EntryLayout";

export const metadata: Metadata = {
  title: "Influ-Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-y-scroll">
      <body className="antialiased min-h-screen flex flex-col relative bg-black">
        <ReduxProvider>
          <MainLayout>{children}</MainLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
