"use client ";
import type { Metadata } from "next";
import "../globals.css";
import SearchBar from "@/components/Navbar";
import { ReduxProvider } from "../providers/redux-providers";
import TopLoader from "@/components/TopLoader";
import SvgPattern from "@/components/SvgPattern";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-y-scroll">
      <body className="antialiased min-h-screen flex flex-col relative bg-black">
        <ReduxProvider>
          <div className="fixed inset-0 z-0">
            <SvgPattern />
          </div>
          <TopLoader />
          <div className="flex flex-1 w-full relative z-10">
            <div className="flex-1 flex flex-col">
              <SearchBar />
              <div className="flex-1">{children}</div>
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
