import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "./providers/redux-providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Header /> */}
      {/* <ReduxProvider> */}
      <body className={` antialiased`}>{children}</body>
      {/* </ReduxProvider> */}
    </html>
  );
}
